name: front-end-tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv install python-dotenv
      - name: Run front-end tests with pytest
        env: 
          PYTHONPATH: ${{ github.workspace }}/web-app
        run: |
          cd web-app
          pipenv run pytest tests/